### ISSUE TITLE
[Forge] Fails to load if excluded an entity

### ISSUE THREAD

**Issue by kaiyalith** [Globox1997/RpgZ#10]
I'm using this mod on both server and client-side, I tried to exclude an entity due reason of having a farm that collects loot (in this case, slimes) in server's config file.
I did typed the the string right, I double-checked it. I'm not sure if I did anything wrong.

This is how it looks like:
```
hopper_extracting = false
despawn_immediately_when_empty = true
despawn_corps_after_ticks = 4800
drop_after_ticks = 2400
#Example: minecraft:zombie or adventurez.brown_fungus
excluded_entities = [minecraft:slime]
drop_unlooted = false
```

And here's the crash log:
```
[11May2021 21:18:13.891] [main/FATAL] [net.minecraftforge.fml.ModLoader/LOADING]: Failed to complete lifecycle event CONSTRUCT, 1 errors found
--
787 | [11May2021 21:18:14.025] [main/DEBUG] [net.minecraftforge.fml.ForgeI18n/CORE]: Loading I18N data entries: 4978
788 | [11May2021 21:18:14.151] [main/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID a36be5e2-981b-4c36-8db6-112bd702231b
789 | [11May2021 21:18:14.178] [main/INFO] [STDOUT/]: [net.minecraft.crash.CrashReport:func_85057_a:196]: Negative index in crash report handler (16/18)
790 | [11May2021 21:18:14.211] [main/FATAL] [net.minecraftforge.fml.server.ServerModLoader/]: Crash report saved to ./crash-reports/crash-2021-05-11_21.18.14-fml.txt
791 | [11May2021 21:18:14.215] [main/FATAL] [net.minecraft.server.Main/]: Failed to start the minecraft server
792 | net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
793 | RpgZ (rpgz) has failed to load correctly
794 | §7com.electronwill.nightconfig.core.io.ParsingException: Invalid value: minecraft:slime
795 | ]
796 | at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:263) ~[forge:?]
797 | at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:230) ~[forge:?]
798 | at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:188) ~[forge:?]
799 | at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:44) ~[forge:?]
800 | at net.minecraft.server.Main.main(Main.java:95) ~[?:?]
801 | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_292]
802 | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_292]
803 | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292]
804 | at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292]
805 | at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge.jar:36.1]
806 | at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?]
807 | at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?]
808 | at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?]
809 | at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?]
810 | at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?]
811 | at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge.jar:?]
812 | at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge.jar:?]
813 | at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge.jar:?]
```

**Comment by HollowayPL** [comment]
Mayby u should use excluded_entities = ["minecraft:slime"] with { " }. That's important. But , i think it's not working in game because I'll tried with minecraft:cow ,pig , and chicken.... i need this to farm in minecolonies ,but nothink change.
I play on 1.16.5 with RAD 2 MODPACK. Mayby other mod is the reason why it not working . 
But i change drop_unlooted = false on true , then citizens can take items after body's gone.
